# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /users
    controller: 'funcionListadoUsuarios'
    methods:
      - GET

ruta_result_list:
    path:     /results
    controller: 'funcionListadoResultados'
    methods:
        - GET

ruta_create_user:
    path:     /create/user
    controller: 'funcionCrearUsuario'
    methods:
        - GET
        - POST

ruta_create_result:
    path:     /create/result
    controller: 'funcionCrearResultado'
    methods:
        - GET
        - POST

ruta_delete_user:
    path:     /users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET

ruta_delete_result:
    path:     /results/{name}
    controller: 'funcionResultado'
    defaults:
        name: _default_
    methods:
        - GET

ruta_update_user:
    path:     /users/update/{name}
    controller: 'funcionActualizarUsuario'
    defaults:
        name: _default_
    methods:
        - GET
        - POST

ruta_update_result:
    path:     /result/update/{name}
    controller: 'funcionActualizarResultado'
    defaults:
        name: _default_
    methods:
        - GET
        - POST